<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Customer.Domain/Customer.Domain.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Common/BuildingBlocks.Common.csproj" />
    <ProjectReference Include="../../BuildingBlocks/EventBus/BuildingBlocks.EventBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="$(MediatRVersion)" />
    <PackageReference Include="FluentValidation" Version="$(FluentValidationVersion)" />
    <PackageReference Include="AutoMapper" Version="$(AutoMapperVersion)" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="$(AutoMapperExtensionsVersion)" />
  </ItemGroup>

</Project>
