<Project>
  <!-- Target framework -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <!-- Package versions -->
  <PropertyGroup>
    <MicrosoftExtensionsLoggingAbstractionsVersion>10.0.2</MicrosoftExtensionsLoggingAbstractionsVersion>
    <MicrosoftExtensionsConfigurationAbstractionsVersion>10.0.2</MicrosoftExtensionsConfigurationAbstractionsVersion>
    <MicrosoftExtensionsConfigurationBinderVersion>10.0.2</MicrosoftExtensionsConfigurationBinderVersion>
    <MicrosoftExtensionsHostingAbstractionsVersion>10.0.2</MicrosoftExtensionsHostingAbstractionsVersion>
    <FluentValidationVersion>12.1.1</FluentValidationVersion>
    <MediatRContractsVersion>2.0.1</MediatRContractsVersion>
    <RabbitMQClientVersion>6.8.1</RabbitMQClientVersion>
    <ConfluentKafkaVersion>2.13.0</ConfluentKafkaVersion>
    <MicrosoftExtensionsDependencyInjectionAbstractionsVersion>10.0.2</MicrosoftExtensionsDependencyInjectionAbstractionsVersion>
    <PollyVersion>8.6.5</PollyVersion>
    <MicrosoftEntityFrameworkCoreVersion>10.0.2</MicrosoftEntityFrameworkCoreVersion>
    <MicrosoftEntityFrameworkCoreSqlServerVersion>10.0.2</MicrosoftEntityFrameworkCoreSqlServerVersion>
    <MicrosoftEntityFrameworkCoreDesignVersion>10.0.2</MicrosoftEntityFrameworkCoreDesignVersion>
    <MediatRVersion>14.0.0</MediatRVersion>
  </PropertyGroup>

  <!-- Code analysis -->
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <!-- Source link -->
  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <!-- Deterministic builds -->
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>